const SPANISH_WORDS = [
  "playa",
  "montaña",
  "río",
  "lago",
  "océano",
  "mar",
  "isla",
  "bosque",
  "selva",
  "desierto",
  "cascada",
  "cueva",
  "volcán",
  "valle",
  "colina",
  "acantilado",
  "bahía",
  "costa",
  "península",
  "glaciar",
  "pantano",
  "laguna",
  "arroyo",
  "pradera",
  "campo",
  "jardín",
  "parque",
  "plaza",
  "calle",
  "avenida",
  "puente",
  "túnel",
  "carretera",
  "autopista",
  "sendero",
  "camino",
  "pueblo",
  "ciudad",
  "barrio",
  "capital",
  "aeropuerto",
  "estación",
  "puerto",
  "terminal",
  "muelle",
  "faro",
  "frontera",
  "aduana",
  "embajada",
  "hotel",
  "hostal",
  "camping",
  "cabaña",
  "refugio",
  "mirador",
  "reserva",
  "zoológico",
  "acuario",
  "granja",
  "viñedo",
  "mercado",
  "supermercado",
  "tienda",
  "panadería",
  "carnicería",
  "pescadería",
  "farmacia",
  "hospital",
  "clínica",
  "consultorio",
  "escuela",
  "colegio",
  "universidad",
  "biblioteca",
  "museo",
  "teatro",
  "cine",
  "restaurante",
  "cafetería",
  "bar",
  "discoteca",
  "estadio",
  "gimnasio",
  "piscina",
  "iglesia",
  "catedral",
  "templo",
  "mezquita",
  "sinagoga",
  "monasterio",
  "castillo",
  "palacio",
  "torre",
  "rascacielos",
  "ayuntamiento",
  "oficina",
  "banco",
  "correos",
  "comisaría",
  "bomberos",
  "parada",
  "metro",
  "tren",
  "tranvía",
  "autobús",
  "taxi",
  "garaje",
  "aparcamiento",
  "gasolinera",
  "taller",
  "ferretería",
  "peluquería",
  "lavandería",
  "floristería",
  "librería",
  "juguetería",
  "zapatería",
  "joyería",
  "pastelería",
  "heladería",
  "centro",
  "centro comercial",
  "parque infantil",
  "cancha",
  "pista",
  "campo de fútbol",
  "campo de golf",
  "tribunal",
  "cárcel",
  "cementerio",
  "playa nudista",
  "balneario",
  "spa",
  "sauna",
  "oficina de turismo",
  "aula",
  "laboratorio",
  "auditorio",
  "comedor",
  "cocina",
  "baño",
  "dormitorio",
  "sala",
  "salón",
  "garaje privado",
  "terraza",
  "balcón",
  "patio",
  "azotea",
  "sótano",
  "ático",
  "ascensor",
  "escalera",
  "pasillo",
  "entrada",
  "salida",
  "recepción",
  "taquilla",
  "andén",
  "puerta",
  "ventana",
  "techo",
  "pared",
  "suelo",
  "jardín botánico",
  "planetario",
  "observatorio",
  "circuito",
  "estudio",
  "set de cine",
  "playa artificial",
  "pista de hielo",
  "pista de baile",
  "sala de espera",
  "sala de reuniones",
  "sala de conciertos",
  "parque nacional",
  "parque acuático",
  "parque de atracciones",
  "parque temático",
  "mesa",
  "silla",
  "sofá",
  "cama",
  "almohada",
  "manta",
  "colchón",
  "armario",
  "cajón",
  "estantería",
  "lámpara",
  "bombilla",
  "interruptor",
  "enchufe",
  "cargador",
  "cable",
  "batería",
  "reloj",
  "despertador",
  "calendario",
  "espejo",
  "cuadro",
  "alfombra",
  "cortina",
  "persiana",
  "maceta",
  "florero",
  "vela",
  "llave",
  "cerradura",
  "candado",
  "mochila",
  "maleta",
  "bolso",
  "cartera",
  "monedero",
  "billete",
  "moneda",
  "tarjeta",
  "pasaporte",
  "documento",
  "sobre",
  "sello",
  "postal",
  "cuaderno",
  "libreta",
  "papel",
  "lápiz",
  "bolígrafo",
  "pluma",
  "marcador",
  "borrador",
  "regla",
  "tijeras",
  "pegamento",
  "grapadora",
  "clip",
  "carpeta",
  "archivo",
  "libro",
  "revista",
  "periódico",
  "mapa",
  "diccionario",
  "agenda",
  "diario",
  "teléfono",
  "móvil",
  "computadora",
  "ordenador",
  "tableta",
  "teclado",
  "ratón",
  "pantalla",
  "impresora",
  "escáner",
  "cámara",
  "auriculares",
  "micrófono",
  "altavoz",
  "televisión",
  "radio",
  "control remoto",
  "consola",
  "videojuego",
  "disco",
  "película",
  "serie",
  "aplicación",
  "contraseña",
  "correo",
  "mensaje",
  "foto",
  "vídeo",
  "selfi",
  "drone",
  "reproductor",
  "router",
  "wifi",
  "antena",
  "nevera",
  "refrigerador",
  "congelador",
  "horno",
  "microondas",
  "estufa",
  "tostadora",
  "licuadora",
  "batidora",
  "cafetera",
  "tetera",
  "olla",
  "sartén",
  "cuchillo",
  "tenedor",
  "cuchara",
  "plato",
  "vaso",
  "taza",
  "copa",
  "botella",
  "jarra",
  "servilleta",
  "mantel",
  "tabla",
  "colador",
  "rallador",
  "abrelatas",
  "sacacorchos",
  "escoba",
  "trapeador",
  "aspiradora",
  "lavadora",
  "secadora",
  "plancha",
  "jabón",
  "champú",
  "toalla",
  "cepillo",
  "peine",
  "pasta dental",
  "desodorante",
  "perfume",
  "maquillaje",
  "crema",
  "pañuelo",
  "paraguas",
  "gafas",
  "lentes",
  "sombrero",
  "gorra",
  "camisa",
  "camiseta",
  "pantalón",
  "falda",
  "vestido",
  "abrigo",
  "chaqueta",
  "suéter",
  "bufanda",
  "guantes",
  "calcetines",
  "zapatos",
  "botas",
  "sandalias",
  "cinturón",
  "corbata",
  "anillo",
  "collar",
  "pulsera",
  "reloj de pulsera",
  "maletín",
  "uniforme",
  "disfraz",
  "máscara",
  "casco",
  "linterna",
  "martillo",
  "taladro",
  "serrucho",
  "clavo",
  "tornillo",
  "cinta",
  "cuerda",
  "cadena",
  "manguera",
  "cubo",
  "pala",
  "rastrillo",
  "semilla",
  "tierra",
  "fertilizante",
  "macetero",
  "barbacoa",
  "parrilla",
  "carbón",
  "herramienta",
  "botiquín",
  "termómetro",
  "medicina",
  "pastilla",
  "mascarilla",
  "radiografía",
  "receta",
  "boleto",
  "ticket",
  "invitación",
  "regalo",
  "caja",
  "paquete",
  "bolsa",
  "canasta",
  "carrito",
  "pan",
  "queso",
  "leche",
  "huevo",
  "mantequilla",
  "yogur",
  "cereal",
  "avena",
  "arroz",
  "pasta",
  "sopa",
  "ensalada",
  "pollo",
  "carne",
  "cerdo",
  "pescado",
  "marisco",
  "atún",
  "salmón",
  "jamón",
  "salchicha",
  "hamburguesa",
  "pizza",
  "taco",
  "burrito",
  "quesadilla",
  "nachos",
  "paella",
  "tortilla",
  "empanada",
  "arepa",
  "pupusa",
  "tamal",
  "ceviche",
  "sushi",
  "ramen",
  "curry",
  "falafel",
  "kebab",
  "croissant",
  "donut",
  "galleta",
  "pastel",
  "tarta",
  "churro",
  "flan",
  "helado",
  "chocolate",
  "caramelo",
  "miel",
  "azúcar",
  "sal",
  "pimienta",
  "aceite",
  "vinagre",
  "salsa",
  "mayonesa",
  "mostaza",
  "kétchup",
  "manzana",
  "pera",
  "plátano",
  "banana",
  "naranja",
  "mandarina",
  "limón",
  "lima",
  "uva",
  "fresa",
  "frambuesa",
  "arándano",
  "cereza",
  "sandía",
  "melón",
  "piña",
  "mango",
  "papaya",
  "kiwi",
  "durazno",
  "melocotón",
  "ciruela",
  "coco",
  "aguacate",
  "tomate",
  "cebolla",
  "ajo",
  "zanahoria",
  "patata",
  "papa",
  "batata",
  "lechuga",
  "espinaca",
  "brócoli",
  "coliflor",
  "pepino",
  "calabacín",
  "berenjena",
  "pimiento",
  "maíz",
  "frijol",
  "lenteja",
  "garbanzo",
  "guisante",
  "champíñón",
  "seta",
  "nuez",
  "almendra",
  "cacahuete",
  "pistacho",
  "café",
  "té",
  "agua",
  "jugo",
  "zumo",
  "limonada",
  "refresco",
  "batido",
  "smoothie",
  "cerveza",
  "vino",
  "sidra",
  "champán",
  "cóctel",
  "horchata",
  "mate",
  "chocolate caliente",
  "sándwich",
  "bocadillo",
  "panqueque",
  "crepa",
  "waffle",
  "muffin",
  "palomitas",
  "tostada",
  "mermelada",
  "sopa de tomate",
  "sopa de pollo",
  "caldo",
  "guiso",
  "perro",
  "gato",
  "caballo",
  "vaca",
  "toro",
  "oveja",
  "cabra",
  "gallina",
  "gallo",
  "pato",
  "ganso",
  "pavo",
  "conejo",
  "hámster",
  "rata",
  "ardilla",
  "castor",
  "zorro",
  "lobo",
  "oso",
  "ciervo",
  "mono",
  "gorila",
  "chimpancé",
  "orangután",
  "lemur",
  "león",
  "tigre",
  "pantera",
  "leopardo",
  "jaguar",
  "guepardo",
  "elefante",
  "jirafa",
  "cebra",
  "rinoceronte",
  "hipopótamo",
  "camello",
  "dromedario",
  "llama",
  "alpaca",
  "koala",
  "canguro",
  "panda",
  "oso polar",
  "pingüino",
  "foca",
  "morsa",
  "delfín",
  "ballena",
  "orca",
  "tiburón",
  "pulpo",
  "calamar",
  "medusa",
  "cangrejo",
  "langosta",
  "camarón",
  "pez",
  "tortuga",
  "cocodrilo",
  "caimán",
  "serpiente",
  "lagarto",
  "iguana",
  "camaleón",
  "rana",
  "sapo",
  "águila",
  "halcón",
  "búho",
  "lechuza",
  "paloma",
  "cuervo",
  "loro",
  "canario",
  "flamenco",
  "cisne",
  "pavo real",
  "avestruz",
  "colibrí",
  "gaviota",
  "pelícano",
  "abeja",
  "avispa",
  "hormiga",
  "mariposa",
  "mosquito",
  "mosca",
  "araña",
  "escorpión",
  "caracol",
  "babosa",
  "lombriz",
  "grillo",
  "saltamontes",
  "cucaracha",
  "libélula",
  "mariquita",
  "polilla",
  "termita",
  "pulga",
  "garrapata",
  "erizo",
  "armadillo",
  "perezoso",
  "suricata",
  "médico",
  "médica",
  "enfermero",
  "enfermera",
  "dentista",
  "profesor",
  "profesora",
  "maestro",
  "maestra",
  "estudiante",
  "ingeniero",
  "ingeniera",
  "arquitecto",
  "arquitecta",
  "abogado",
  "abogada",
  "juez",
  "policía",
  "detective",
  "bombero",
  "bombera",
  "piloto",
  "azafata",
  "chef",
  "cocinero",
  "cocinera",
  "camarero",
  "camarera",
  "panadero",
  "panadera",
  "carnicero",
  "pescadero",
  "granjero",
  "jardinero",
  "carpintero",
  "electricista",
  "fontanero",
  "plomero",
  "mecánico",
  "taxista",
  "conductor",
  "conductora",
  "repartidor",
  "mensajero",
  "cartero",
  "guardia",
  "soldado",
  "marinero",
  "astronauta",
  "científico",
  "científica",
  "biólogo",
  "químico",
  "físico",
  "matemático",
  "programador",
  "programadora",
  "diseñador",
  "diseñadora",
  "artista",
  "pintor",
  "pintora",
  "escultor",
  "fotógrafo",
  "fotógrafa",
  "actor",
  "actriz",
  "cantante",
  "músico",
  "bailarín",
  "bailarina",
  "escritor",
  "escritora",
  "poeta",
  "periodista",
  "reportero",
  "locutor",
  "presentador",
  "director",
  "productor",
  "editor",
  "traductor",
  "intérprete",
  "bibliotecario",
  "veterinario",
  "farmacéutico",
  "psicólogo",
  "terapeuta",
  "nutricionista",
  "entrenador",
  "atleta",
  "futbolista",
  "tenista",
  "nadador",
  "ciclista",
  "boxeador",
  "árbitro",
  "payaso",
  "mago",
  "modelo",
  "peluquero",
  "barbero",
  "maquillador",
  "sastre",
  "costurera",
  "zapatero",
  "joyero",
  "relojero",
  "cajero",
  "vendedor",
  "dependiente",
  "gerente",
  "empresario",
  "secretario",
  "recepcionista",
  "contador",
  "economista",
  "banquero",
  "corredor",
  "alcalde",
  "presidente",
  "ministro",
  "rey",
  "reina",
  "príncipe",
  "princesa",
  "emperador",
  "monje",
  "sacerdote",
  "pastor",
  "rabí",
  "imán",
  "guía",
  "turista",
  "vecino",
  "amigo",
  "familia",
  "madre",
  "padre",
  "hijo",
  "hija",
  "hermano",
  "hermana",
  "abuelo",
  "abuela",
  "nieto",
  "nieta",
  "tío",
  "tía",
  "primo",
  "prima",
  "sobrino",
  "sobrina",
  "bebé",
  "niño",
  "niña",
  "adolescente",
  "adulto",
  "coche",
  "auto",
  "carro",
  "camioneta",
  "camión",
  "bus",
  "bicicleta",
  "motocicleta",
  "moto",
  "patinete",
  "monopatín",
  "avión",
  "helicóptero",
  "globo",
  "cohete",
  "barco",
  "bote",
  "lancha",
  "yate",
  "crucero",
  "submarino",
  "canoa",
  "kayak",
  "velero",
  "ferri",
  "ambulancia",
  "patrulla",
  "camión de bomberos",
  "tractor",
  "excavadora",
  "grúa",
  "carreta",
  "trineo",
  "carroza",
  "limusina",
  "caravana",
  "Albert Einstein",
  "Pablo Picasso",
  "Leonardo da Vinci",
  "William Shakespeare",
  "Cristóbal Colón",
  "Napoleón",
  "Cleopatra",
  "Julio César",
  "George Washington",
  "Marie Curie",
  "Isaac Newton",
  "Elon Musk",
  "Barack Obama",
  "Donald Trump",
  "Reina Isabel",
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Rafael Nadal",
  "Bad Bunny",
  "Ricky Martin",
  "Jennifer López",
  "Enrique Iglesias",
  "Madonna",
  "Michael Jackson",
  "Elvis Presley",
  "Justin Bieber",
  "Tom Cruise",
  "Brad Pitt",
  "George Clooney",
  "Antonio Banderas",
  "Sandra Bullock",
  "Angelina Jolie",
  "Mickey Mouse",
  "Simba",
  "Aladdín",
  "Ariel",
  "James Bond",
  "Harry Potter",
  "Luke Skywalker",
  "Indiana Jones",
  "Spiderman",
  "Batman",
  "Superman",
];

const ENGLISH_TRANSLATIONS = [
  // 1-100
  `beach|mountain|river|lake|ocean|sea|island|forest|jungle|desert|waterfall|cave|volcano|valley|hill|cliff|bay|coast|peninsula|glacier|swamp|lagoon|stream|meadow|field|garden|park|square|street|avenue|bridge|tunnel|road|highway|trail|path|town|city|neighbourhood|capital|airport|station|port|terminal|pier|lighthouse|border|customs|embassy|hotel|hostel|campground|cabin|shelter|lookout|reserve|zoo|aquarium|farm|vineyard|market|supermarket|store|bakery|butcher shop|fish market|pharmacy|hospital|clinic|doctor's office|school|high school|university|library|museum|theatre|cinema|restaurant|café|bar|nightclub|stadium|gym|swimming pool|church|cathedral|temple|mosque|synagogue|monastery|castle|palace|tower|skyscraper|city hall|office|bank|post office|police station|fire station`,
  // 101-200
  `stop|subway|train|streetcar|bus|taxi|garage|parking lot|gas station|repair shop|hardware store|hair salon|laundromat|flower shop|bookstore|toy store|shoe store|jewellery store|pastry shop|ice cream shop|downtown|shopping mall|playground|court|track|soccer field|golf course|courthouse|prison|cemetery|nudist beach|resort|spa|sauna|tourist office|classroom|laboratory|auditorium|dining room|kitchen|bathroom|bedroom|room|living room|private garage|terrace|balcony|patio|rooftop|basement|attic|elevator|stairs|hallway|entrance|exit|reception|ticket office|platform|door|window|ceiling|wall|floor|botanical garden|planetarium|observatory|circuit|studio|film set|artificial beach|ice rink|dance floor|waiting room|meeting room|concert hall|national park|water park|amusement park|theme park|table|chair|sofa|bed|pillow|blanket|mattress|wardrobe|drawer|shelf|lamp|light bulb|switch|outlet|charger|cable|battery|clock|alarm clock|calendar`,
  // 201-300
  `mirror|painting|rug|curtain|blind|flowerpot|vase|candle|key|lock|padlock|backpack|suitcase|handbag|wallet|coin purse|banknote|coin|card|passport|document|envelope|stamp|postcard|notebook|notepad|paper|pencil|pen|fountain pen|marker|eraser|ruler|scissors|glue|stapler|paper clip|folder|file|book|magazine|newspaper|map|dictionary|planner|diary|telephone|cellphone|computer|computer|tablet|keyboard|mouse|screen|printer|scanner|camera|headphones|microphone|speaker|television|radio|remote control|console|video game|disc|movie|series|app|password|email|message|photo|video|selfie|drone|player|router|Wi-Fi|antenna|fridge|refrigerator|freezer|oven|microwave|stove|toaster|blender|mixer|coffee maker|kettle|pot|frying pan|knife|fork|spoon|plate|glass|mug|wine glass`,
  // 301-400
  `bottle|pitcher|napkin|tablecloth|board|strainer|grater|can opener|corkscrew|broom|mop|vacuum cleaner|washing machine|dryer|iron|soap|shampoo|towel|brush|comb|toothpaste|deodorant|perfume|makeup|cream|handkerchief|umbrella|glasses|lenses|hat|cap|shirt|T-shirt|pants|skirt|dress|coat|jacket|sweater|scarf|gloves|socks|shoes|boots|sandals|belt|tie|ring|necklace|bracelet|wristwatch|briefcase|uniform|costume|mask|helmet|flashlight|hammer|drill|handsaw|nail|screw|tape|rope|chain|hose|bucket|shovel|rake|seed|soil|fertilizer|planter|barbecue|grill|charcoal|tool|first aid kit|thermometer|medicine|pill|face mask|X-ray|prescription|ticket|ticket|invitation|gift|box|package|bag|basket|shopping cart|bread|cheese|milk|egg|butter|yogurt|cereal`,
  // 401-500
  `oats|rice|pasta|soup|salad|chicken|meat|pork|fish|seafood|tuna|salmon|ham|sausage|hamburger|pizza|taco|burrito|quesadilla|nachos|paella|omelette|empanada|arepa|pupusa|tamale|ceviche|sushi|ramen|curry|falafel|kebab|croissant|doughnut|cookie|cake|pie|churro|flan|ice cream|chocolate|candy|honey|sugar|salt|pepper|oil|vinegar|sauce|mayonnaise|mustard|ketchup|apple|pear|plantain|banana|orange|mandarin|lemon|lime|grape|strawberry|raspberry|blueberry|cherry|watermelon|melon|pineapple|mango|papaya|kiwi|nectarine|peach|plum|coconut|avocado|tomato|onion|garlic|carrot|potato|potato|sweet potato|lettuce|spinach|broccoli|cauliflower|cucumber|zucchini|eggplant|bell pepper|corn|bean|lentil|chickpea|pea|button mushroom|mushroom|walnut|almond`,
  // 501-600
  `peanut|pistachio|coffee|tea|water|juice|juice|lemonade|soft drink|milkshake|smoothie|beer|wine|cider|champagne|cocktail|horchata|mate|hot chocolate|sandwich|sub sandwich|pancake|crêpe|waffle|muffin|popcorn|toast|jam|tomato soup|chicken soup|broth|stew|dog|cat|horse|cow|bull|sheep|goat|hen|rooster|duck|goose|turkey|rabbit|hamster|rat|squirrel|beaver|fox|wolf|bear|deer|monkey|gorilla|chimpanzee|orangutan|lemur|lion|tiger|panther|leopard|jaguar|cheetah|elephant|giraffe|zebra|rhinoceros|hippopotamus|camel|dromedary|llama|alpaca|koala|kangaroo|panda|polar bear|penguin|seal|walrus|dolphin|whale|orca|shark|octopus|squid|jellyfish|crab|lobster|shrimp|fish|turtle|crocodile|alligator|snake|lizard|iguana|chameleon|frog|toad`,
  // 601-700
  `eagle|falcon|owl|barn owl|dove|crow|parrot|canary|flamingo|swan|peacock|ostrich|hummingbird|seagull|pelican|bee|wasp|ant|butterfly|mosquito|fly|spider|scorpion|snail|slug|earthworm|cricket|grasshopper|cockroach|dragonfly|ladybug|moth|termite|flea|tick|hedgehog|armadillo|sloth|meerkat|doctor|doctor|nurse|nurse|dentist|teacher|teacher|teacher|teacher|student|engineer|engineer|architect|architect|lawyer|lawyer|judge|police officer|detective|firefighter|firefighter|pilot|flight attendant|chef|cook|cook|waiter|waitress|baker|baker|butcher|fishmonger|farmer|gardener|carpenter|electrician|plumber|plumber|mechanic|taxi driver|driver|driver|delivery person|courier|mail carrier|guard|soldier|sailor|astronaut|scientist|scientist|biologist|chemist|physicist|mathematician|programmer|programmer|designer|designer|artist|painter`,
  // 701-800
  `painter|sculptor|photographer|photographer|actor|actress|singer|musician|dancer|dancer|writer|writer|poet|journalist|reporter|announcer|host|director|producer|editor|translator|interpreter|librarian|veterinarian|pharmacist|psychologist|therapist|nutritionist|coach|athlete|soccer player|tennis player|swimmer|cyclist|boxer|referee|clown|magician|model|hairdresser|barber|makeup artist|tailor|seamstress|shoemaker|jeweller|watchmaker|cashier|salesperson|shop assistant|manager|businessperson|secretary|receptionist|accountant|economist|banker|runner|mayor|president|minister|king|queen|prince|princess|emperor|monk|priest|pastor|rabbi|imam|guide|tourist|neighbour|friend|family|mother|father|son|daughter|brother|sister|grandfather|grandmother|grandson|granddaughter|uncle|aunt|cousin|cousin|nephew|niece|baby|boy|girl|teenager|adult|car|car|car`,
  // 801-876
  `pickup truck|truck|bus|bicycle|motorcycle|motorbike|scooter|skateboard|airplane|helicopter|balloon|rocket|ship|boat|speedboat|yacht|cruise ship|submarine|canoe|kayak|sailboat|ferry|ambulance|police car|fire truck|tractor|excavator|crane|cart|sled|carriage|limousine|camper van|Albert Einstein|Pablo Picasso|Leonardo da Vinci|William Shakespeare|Christopher Columbus|Napoleon|Cleopatra|Julius Caesar|George Washington|Marie Curie|Isaac Newton|Elon Musk|Barack Obama|Donald Trump|Queen Elizabeth|Lionel Messi|Cristiano Ronaldo|Rafael Nadal|Bad Bunny|Ricky Martin|Jennifer Lopez|Enrique Iglesias|Madonna|Michael Jackson|Elvis Presley|Justin Bieber|Tom Cruise|Brad Pitt|George Clooney|Antonio Banderas|Sandra Bullock|Angelina Jolie|Mickey Mouse|Simba|Aladdin|Ariel|James Bond|Harry Potter|Luke Skywalker|Indiana Jones|Spider-Man|Batman|Superman`,
]
  .join("|")
  .split("|");

if (SPANISH_WORDS.length !== ENGLISH_TRANSLATIONS.length) {
  throw new Error("Spanish words and English translations must stay aligned.");
}

const WORDS = SPANISH_WORDS.map((word, index) => ({
  word,
  translation: ENGLISH_TRANSLATIONS[index],
}));

const MIN_PLAYERS = 3;
const MAX_PLAYERS = 12;

const state = {
  playerCount: 4,
  currentPlayer: 0,
  impostorIndex: 0,
  word: null,
};

const elements = {
  setupScreen: document.querySelector("#setup-screen"),
  gameScreen: document.querySelector("#game-screen"),
  readyScreen: document.querySelector("#ready-screen"),
  playerCount: document.querySelector("#player-count"),
  decreasePlayers: document.querySelector("#decrease-players"),
  increasePlayers: document.querySelector("#increase-players"),
  startGame: document.querySelector("#start-game"),
  showRules: document.querySelector("#show-rules"),
  rulesDialog: document.querySelector("#rules-dialog"),
  closeRules: document.querySelector("#close-rules"),
  quitGame: document.querySelector("#quit-game"),
  progressDots: document.querySelector("#progress-dots"),
  progressCount: document.querySelector("#progress-count"),
  handoffView: document.querySelector("#handoff-view"),
  playerHeading: document.querySelector("#player-heading"),
  privacyNumber: document.querySelector(".privacy-symbol span"),
  readyButton: document.querySelector("#ready-button"),
  cardView: document.querySelector("#card-view"),
  cardPlayerNumber: document.querySelector("#card-player-number"),
  secretCard: document.querySelector("#secret-card"),
  cardFront: document.querySelector(".card-front"),
  roleLabel: document.querySelector("#role-label"),
  secretWord: document.querySelector("#secret-word"),
  wordTranslation: document.querySelector("#word-translation"),
  roleHint: document.querySelector("#role-hint"),
  nextPlayer: document.querySelector("#next-player"),
  newRound: document.querySelector("#new-round"),
  changePlayers: document.querySelector("#change-players"),
};

function randomIndex(length) {
  if (window.crypto?.getRandomValues) {
    const values = new Uint32Array(1);
    window.crypto.getRandomValues(values);
    return values[0] % length;
  }

  return Math.floor(Math.random() * length);
}

function updatePlayerCount(amount) {
  state.playerCount = Math.min(
    MAX_PLAYERS,
    Math.max(MIN_PLAYERS, state.playerCount + amount),
  );
  elements.playerCount.textContent = state.playerCount;
  elements.decreasePlayers.disabled = state.playerCount === MIN_PLAYERS;
  elements.increasePlayers.disabled = state.playerCount === MAX_PLAYERS;
}

function showScreen(screen) {
  [elements.setupScreen, elements.gameScreen, elements.readyScreen].forEach(
    (item) => {
      item.hidden = item !== screen;
    },
  );
}

function buildProgress() {
  elements.progressDots.replaceChildren();

  for (let index = 0; index < state.playerCount; index += 1) {
    const dot = document.createElement("span");
    dot.className = "progress-dot";
    if (index < state.currentPlayer) dot.classList.add("done");
    if (index === state.currentPlayer) dot.classList.add("current");
    elements.progressDots.append(dot);
  }

  elements.progressCount.textContent = `${state.currentPlayer + 1} / ${state.playerCount}`;
}

function preparePlayer() {
  const playerNumber = state.currentPlayer + 1;
  elements.playerHeading.textContent = `Jugador ${playerNumber}`;
  elements.privacyNumber.textContent = playerNumber;
  elements.cardPlayerNumber.textContent = playerNumber;
  elements.handoffView.hidden = false;
  elements.cardView.hidden = true;
  elements.secretCard.classList.remove("is-flipped");
  elements.nextPlayer.textContent =
    state.currentPlayer === state.playerCount - 1
      ? "Ocultar y empezar"
      : `Ocultar y pasar al jugador ${playerNumber + 1}`;
  buildProgress();
}

function setCardContent() {
  const isImpostor = state.currentPlayer === state.impostorIndex;
  elements.cardFront.classList.toggle("impostor", isImpostor);
  elements.roleLabel.textContent = isImpostor ? "Tu rol es" : "Tu palabra es";
  elements.secretWord.textContent = isImpostor
    ? "IMPOSTOR"
    : state.word.word.toLocaleUpperCase("es");
  elements.wordTranslation.textContent = isImpostor
    ? ""
    : state.word.translation;
  elements.wordTranslation.hidden = isImpostor;
  elements.roleHint.textContent = isImpostor
    ? "Finge que conoces la palabra"
    : "Memorízala bien";
}

function startRound() {
  state.currentPlayer = 0;
  state.impostorIndex = randomIndex(state.playerCount);
  state.word = WORDS[randomIndex(WORDS.length)];
  showScreen(elements.gameScreen);
  preparePlayer();
}

function showPlayerCard() {
  setCardContent();
  elements.handoffView.hidden = true;
  elements.cardView.hidden = false;
  void elements.secretCard.offsetWidth;
  elements.secretCard.classList.add("is-flipped");
  elements.nextPlayer.focus();
}

function advancePlayer() {
  elements.secretCard.classList.remove("is-flipped");

  if (state.currentPlayer === state.playerCount - 1) {
    showScreen(elements.readyScreen);
    return;
  }

  state.currentPlayer += 1;
  preparePlayer();
}

elements.decreasePlayers.addEventListener("click", () => updatePlayerCount(-1));
elements.increasePlayers.addEventListener("click", () => updatePlayerCount(1));
elements.startGame.addEventListener("click", startRound);
elements.showRules.addEventListener("click", () =>
  elements.rulesDialog.showModal(),
);
elements.closeRules.addEventListener("click", () =>
  elements.rulesDialog.close(),
);
elements.rulesDialog.addEventListener("click", (event) => {
  if (event.target === elements.rulesDialog) elements.rulesDialog.close();
});
elements.readyButton.addEventListener("click", showPlayerCard);
elements.nextPlayer.addEventListener("click", advancePlayer);
elements.newRound.addEventListener("click", startRound);
elements.changePlayers.addEventListener("click", () =>
  showScreen(elements.setupScreen),
);
elements.quitGame.addEventListener("click", () =>
  showScreen(elements.setupScreen),
);

updatePlayerCount(0);
